---
    - name: Create 3nic PAYG Cluster - New Stack
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ resourceGroup }}"
        location: "{{ loaction | default('eastus') }}"
        parameters:
          adminUsername:
            value: "{{ adminUsername }}"
          adminPassword:
            value: "{{ adminPassword }}"
          dnsLabel:
            value: "{{ dnsLabel }}"
          instanceName:
            value: "{{ instanceName }}"
          instanceType:
            value: "{{ instanceType }}"
          imageName:
            value: "{{ imageName }}"
          bigIpVersion:
            value: "{{ bigIpVersion }}"
          licensedBandwidth:
            value: "{{ licensedBandwidth }}"
          numberOfExternalIps:
            value: "{{ numberOfExternalIps }}"
          vnetAddressPrefix:
            value: "{{ vnetAddressPrefix }}"
          enableNetworkFailover:
            value: "{{ enableNetworkFailover }}"
          internalLoadBalancerType:
            value: "{{ internalLoadBalancerType }}"
          internalLoadBalancerProbePort:
            value: "{{ internalLoadBlancerProbePort }}"
          ntpServer:
            value: "{{ ntpServer }}"
          timeZone:
            value: "{{ timeZone }}"
          restrictedSrcAddress:
            value: "{{ restrictedSrcAddress }}"
          tagValues:
            value: "{{ tagValues }}"
          allowUsageAnalytics:
            value: "{{ allowUsageAnalytics }}"
        template_link: 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/cluster/3nic/new_stack/PAYG/azuredeploy.json'
